### PR TITLE
Suggest to run tox instead of pytest in hack docs

### PR DESCRIPTION
**Pull request by timofurrer**

### CODE REVIEW

**Comment by jmaupetit** [comment]
Too long and too greedy, I think Travis is here to help with that.

**Comment by k4nar** [comment]
Yes, plus tox only works if you have all the versions of Python supported by Watson installed in your environment.

Instead of replacing pytest by tox in the docs, maybe we could add something about it.

**Comment by jmaupetit** [comment]
:+1: to add something about `tox` vs `pytest` in the docs.

**Comment by SpotlightKid** [comment]
I think contributors can be expected to go to the trouble of at least installing tox and python 2.7 and 3.5 (or  python 3.4, if their distro only provides that). Just makes it easier for them to avoid surprises from failing Travis jobs.

We could remove `py33` and `py34` envs from `tox.ini`, so they don't run by default but still run them on Travis (via `.tavis.yml`).

**Comment by SpotlightKid** [comment]
Tox >= 1.7.2 has a config option [skip_missing_interpreters](https://testrun.org/tox/latest/config.html#confval-skip_missing_interpreters=BOOL), which, when set to `True`, allows to run the tests via tox even if you don't have the Python versions for all specified tox environments installed. If we add this to `tox.ini`, I think we can safely recommend to run `tox` instead of `py.test`.

**Comment by SpotlightKid** [comment]
Closing this in favour of #133.

**Pull request closed without merging**
