### PR TITLE
Add wrapper for `RawConfigParser` to make option access more convenient

### PR DESCRIPTION
**Pull request by SpotlightKid**
See comment on #31 [here](https://github.com/TailorDev/Watson/issues/31#issuecomment-150196100).

### CODE REVIEW

**Comment by SpotlightKid** [comment]
Tests fail on Python 2.7 because `RawConfigParser` is an old-style class there, so `super` can't be used. Fixing it now.

**Comment by SpotlightKid** [comment]
Any thoughts on this?

**Comment by k4nar** [comment]
LGTM

**Comment by waynew** [comment]
:+1: from me (FWIW). My PR #47 depends on this implementation (or the actual config value to be present).

**Comment by jmaupetit** [comment]
:+1:

**Comment by SpotlightKid** [comment]
While looking at #47, I noticed one minor issue. The `ConfigParser` wrapper breaks the `getint`, `getfloat` and `getboolean` methods from the base class. Two solutions:

1. Rename `get` to sth like `getoption`, so it doesn't conflict.
2. Wrap the above mentioned methods as well.

Seems like a lot of trouble, but it would allow to support boolean options like this:

```
[options]
auto_stop = yes
report_current_frame = 0

if config.getboolean('options', 'auto-stop')
    ...
```

I tried to make wrappers that delegate to the base class but it was impossible to do that in a sane way that works in Python 2 and 3. So I basically re-implemented them:

```
class ConfigParser(RawConfigParser):
    """A simple wrapper for RawConfigParser to make options access easier."""

    def get(self, section, option, default=None, **kwargs):
        """
        Return value of option in given configuration section as a string.

        If option is not set, return default instead (defaults to None).

        """
        return (RawConfigParser.get(self, section, option, **kwargs)
                if self.has_option(section, option) else default)

    def getint(self, section, option, default=None):
        val = self.get(section, option, default)
        return val if val is None else int(val)

    def getfloat(self, section, option, default=None):
        val = self.get(section, option, default)
        return val if val is None else float(val)

    def getboolean(self, section, option, default=False):
        val = self.get(section, option)
        return default if val is None else val.lower() in (
            '1', 'on', 'true', 'yes')
   ...
```

I also passed `kwargs` to `RawConfigParser.get()` for more compatibility with Python 3's `configparser`.
Should I update my PR with this?

**Comment by SpotlightKid** [comment]
Moved `ConfigParser` into its own sub-module, because it was getting to long. Added the `getint`, `getfloat` and `getboolean` methods (slightly different than the code above!) with docstrings and tests.

**Comment by jmaupetit** [comment]
:+1:
@SpotlightKid thank you again for your active work.
@k4nar let's merge this!

**Comment by k4nar** [comment]
:tada:

**Pull request merged**
