### PR TITLE
Make formatting styles configurable

### PR DESCRIPTION
**Pull request by SpotlightKid**
Styles can be set via sections in the config file named `style:<element>`, where `<element>` is the name of an element a style can be applied to. Settings in that section are used as parameters to the `click.style` function.

The current list of possible elements is:

- project
- tag
- time
- error
- date
- id

Example config:

```
[style:project]
fg = white
bg = black

[style:tag]
fg = yellow
bg = white
```

Notes:
- This PR depends on PR #139 
- Documentation is not updated yet, it will be added when the reviewers agree this is a good config structure and implementation.
- I had originally contemplated to use a config structure as shown below or similar, but it would have made the config parsing much more complicated.

```
[styles]
project = fg:white bg:black
tag = fg:red
...
```

### CODE REVIEW

**Comment by k4nar** [comment]
Neat :+1:!

Although, may I suggest the following format instead?
```
[style]
project_fg = white
project_bg = black
tag_fg = red
```

**Comment by SpotlightKid** [comment]
I'm not sure, if I like that one better. Makes the options rather verbose and if you don't keep options for one element together, it might become harder to see all options for one element at a glance.

**Comment by k4nar** [comment]
Other proposal, very close to yours:
```
[style:tag]
fg = yellow
bg = white
```

I don't think `:` is part the ini "spec", but I've seen it used before. For example this is what Circus uses.

**Comment by SpotlightKid** [comment]
That would be a single-char change in the code (plus adapting tests).

**Comment by k4nar** [comment]
I guess so yes. That's just a matter of taste, but I find it clearer and more beautiful :) .

**Comment by SpotlightKid** [comment]
Closing this since I'm cleaning my unmerged/unfinished PRs and this hasn't been acted upon in years.

**Pull request closed without merging**
