### PR TITLE
Fix incomplete renaming of  variable (fixes #158)

### LINKED ISSUE #158: Watson config throwing errors
Watson version: 1.5.0

While using the example from the docs (https://tailordev.github.io/Watson/user-guide/configuration/#editing), i get following error:

```
$ watson config backend.token 7e329263e329
Traceback (most recent call last):
  File "/usr/local/bin/watson", line 11, in <module>
    load_entry_point('td-watson==1.5.0', 'console_scripts', 'watson')()
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2652, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2306, in load
    return self.resolve()
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2312, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/watson/__main__.py", line 6, in <module>
    cli.cli()
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/watson/1.5.0/libexec/lib/python2.7/site-packages/watson/cli.py", line 867, in config
    if not config.has_section(section):
AttributeError: 'Command' object has no attribute 'has_section'
```

### PR DESCRIPTION
**Pull request by SpotlightKid**
Signed-off-by: Christopher Arndt <chris@chrisarndt.de>

### CODE REVIEW

**Comment by SpotlightKid** [comment]
* Old line 871 (`watson.config = config`) was unnecessary, because both references already point to the same object.

* We should really have CLI tests.

**Comment by jmaupetit** [comment]
Thank you for this Chris!

> We should really have CLI tests.

Yup. Thought about it yesterday. I will handle this.

**Comment by jmaupetit** [comment]
We'll need to release this in a `1.5.1`

**Comment by willdurand** [comment]
LGTM too. @jmaupetit could you merge and release a new version please?

**Comment by willdurand** [comment]
or someone else with PyPI push access.

**Comment by k4nar** [comment]
I can do the release.

**Comment by k4nar** [comment]
There was only documentation changes so far, so I'll do the 1.5.1 from master.

**Comment by willdurand** [comment]
:+1: perfect and Hi! it's been a long time :)

the doc change was about the release process, so it should be useful to you

**Comment by k4nar** [comment]
Done :) .

**Comment by jmaupetit** [comment]
Thx @k4nar !

**Pull request merged**
