### PR TITLE
Add asciinema demo link

### PR DESCRIPTION
**Pull request by jmaupetit**
The asciinema movie/screenshot replaces the "old" screenshot

### CODE REVIEW

**Comment by willdurand** [comment]
@jmaupetit you can (should?) embed the video

**Comment by jmaupetit** [comment]
That's what I wanted to do first. But, I am not sure it's a good idea for a README that will be also pushed to PyPI.

**Comment by willdurand** [comment]
Why not?

**Comment by jmaupetit** [comment]
I might be wrong, but I am hesitant to embed JS like the following in a README:

```html
<script type="text/javascript" src="https://asciinema.org/a/35918.js" id="asciicast-35918" async></script>
```

But again, maybe I shouldn't be.

**Comment by willdurand** [comment]
It is still valid HTML, and it works well with GitHub, so it should not be an issue on PyPi.

**Comment by jmaupetit** [comment]
Ok then. I'll do this.

**Comment by jmaupetit** [comment]
Mmmh... it seems like github bypasses the `raw` directive...

**Comment by jmaupetit** [comment]
Ok, I'll try this https://github.com/tav/asciinema2gif

**Comment by willdurand** [comment]
Or do this: https://raw.githubusercontent.com/willdurand/dotfiles/master/README.md.

**Comment by jmaupetit** [comment]
So you mean finally rollback to 01c53c3 :smiley_cat:

**Comment by jmaupetit** [comment]
I think this PR is ready to merge now.

**Comment by k4nar** [comment]
Maybe you should remove the screenshot from the repo too. I like this screenshot though :blush: .

**Comment by jmaupetit** [comment]
The screenshot in still integrated in the documentation. No worries :smile:

**Comment by k4nar** [comment]
Great :) .

**Pull request merged**
