### PR TITLE
Add basic ZSH completion

### PR DESCRIPTION
**Pull request by molovo**
Doesn't quite cover all bases yet, but it's a pretty good start.

Adds completion for:
  - All options and commands
  - Frames on the `edit` and `remove` commands
  - Projects and tags (with the preceding +) on the `start` command
  - Options on the `log` and `report` commands (including tag and project completion for those options)

Happy to add any other completions if you think I've missed anything important.

### CODE REVIEW

**Comment by molovo** [comment]
To use the completion file, just rename `watson.zsh-completion` to `_watson` and place it somewhere in your `$fpath`.

**Comment by jmaupetit** [comment]
Thank you for this @molovo! Have you seen @gdetrez PR #92? Can you join your forces on this? :heart:

**Comment by molovo** [comment]
Ah sorry, I wrote this last week before that pull request was created, and didn't check before submitting. @gdetrez's implementation actually seems to be far more extensive than mine anyway, so I'm inclined to close this and help him out with his.

**Comment by jmaupetit** [comment]
:+1: Thank you for this.

**Pull request closed without merging**
