### PR TITLE
Add watson logo to docs & README

### PR DESCRIPTION
**Pull request by jmaupetit**

### CODE REVIEW

**Comment by willdurand** [comment]
Please, ship it!

**Comment by k4nar** [comment]
The logo looks a bit aliased, but it looks good otherwise.

**Comment by SpotlightKid** [comment]
Nice logo! Is there an SVG for it, so we can make a square icon of the circle part (e.g. for notifications)?

**Comment by jmaupetit** [comment]
Thanks :) Should we add an `/assets` directory to the repo with logo sources?

**Pull request merged**
