### PR TITLE
Python 3.5 support - Fix #44

### LINKED ISSUE #44: Python 3.5 env should be added to tox.ini
Arch Linux already has Python 3.5 as the default Python version now.

### PR DESCRIPTION
**Pull request by k4nar**
cf #44

### CODE REVIEW

**Comment by k4nar** [comment]
Ok, so according to https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-140175872 Travis does not have Python 3.5 installed in the build image.

**Comment by SpotlightKid** [comment]
Oh, that's lame! :(

**Comment by k4nar** [comment]
I just tested locally and I had no failure, so I guess there is no hurry and we can wait for Travis to have a better support for 3.5.

**Comment by SpotlightKid** [comment]
Seeing that there has been no activity from travis on the above mentioned issue for a month, maybe include the workaround for `.travis.yml` mentioned in this [later comment](https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143568134)?

Python 3.5 is there and being installed on new distros. Not testing for it is bad, IMHO.

**Comment by jmaupetit** [comment]
:+1:

**Comment by waynew** [comment]
:+1: for getting 3.5 going on Travis. I'm running arch, so you know there's at least one of me :trollface:

**Pull request closed without merging**
