### PR TITLE
Alternative implementation of restart command

### PR DESCRIPTION
**Pull request by SpotlightKid**
Referencing the discussion from #3, this is how I think the `restart` command should work.

### CODE REVIEW

**Comment by jmaupetit** [comment]
:+1:

Thx again @SpotlightKid

**Comment by k4nar** [comment]
Nice work!

We should wait for #47 to be merged to rebase.

**Comment by willdurand** [comment]
mmh, this should be rebased I guess. Many commits are not yours :)

**Comment by k4nar** [comment]
@willdurand : no need to rebase as long as #47 is not merged though :) .

**Comment by SpotlightKid** [comment]
Ok, I'll wait for #47 to be merged, then.

**Comment by SpotlightKid** [comment]
Rebased my commits (rather involved process). Should be ready to be merged. If you have any problems merging, let me know, I still have a copy of the repo with the original history.

**Comment by jmaupetit** [comment]
:+1: looks good to me thanks!

**Comment by k4nar** [comment]
@SpotlightKid : The commits before 0c9bad5 were merged in #47, I think you missed something when rebasing :) .

**Comment by SpotlightKid** [comment]
Hmm, I'm not sure what to do differently. I basically did:

```
git checkout develop
git fetch upstream
git merge upstream/develop
git checkout feature/restart
git merge develop
git rebase develop
```

Conflicts for three patches during the rebasing here, which I solved manually. Afterwards I have a history with commits to the branch on top the other changes. Should I have skipped those patches with conflicts instead?

Then

```
git rebase -i HEAD~9
git push --force-with-lease
```

to squash all the commits into one and overwrite the history in my origin.

Any advice?

**Comment by k4nar** [comment]
@SpotlightKid : Do you want to keep the two commits from @waynew concerning the restart command ? If you want to keep them, use `git rebase -i develop` and drop the first three commits, if not you can squash everything.

**Comment by SpotlightKid** [comment]
Ok, I'll try again later tonight.

**Comment by SpotlightKid** [comment]
Now, that should do it.

**Pull request merged**
