### PR TITLE
Added basic dmenu script to start/stop and view status

### PR DESCRIPTION
**Pull request by firecat53**
Another addition I found useful for starting/stopping Watson when I don't have a terminal open. Just add a keybinding :)

Let me know what you think!

Scott

### CODE REVIEW

**Comment by jmaupetit** [comment]
Hi @firecat53! Thank you for this. It looks really nice, but I think it's a bit too specific to be integrated in the main repository. My advice would be to maintain it in a separate repository you own.

As side contributions are growing, we should document them in the documentation.

But. This is just my opinion. I would like community feedback on this.

**Comment by k4nar** [comment]
Yeah, I think too that is should not be in the main repository. But it looks very great though.

**Comment by SpotlightKid** [comment]
Yeah, I agree that contributions are better kept in separate repositories and linked in the docs.

BTW, I was also thinking about writing a little systray app to monitor and start and stop Watson. Not sure when I'll get around to it, so if anybody else wants to do it, don't hold back ;)

**Comment by jmaupetit** [comment]
@SpotlightKid a few weeks ago I worked on an [electron](http://electron.atom.io/)-based systray to monitor `watson` status and be able to get (native) system notifications. I have not publicly released it yet, but I will soon :) Here is a preview:

screenshot_14_02_16_00_41

screenshot_14_02_16_00_29

**Comment by SpotlightKid** [comment]
@jmaupetit Cool, that's even better than something GTK or Qt based.

**Comment by firecat53** [comment]
Ok, thanks. Repo setup here:  https://github.com/firecat53/watson-dmenu

Let me know if anyone finds it useful or if there are additional features that could be added.

Scott

**Comment by jmaupetit** [comment]
Thank you again for your work Scott. Let's keep in touch on this.

**Pull request closed without merging**
