### PR TITLE
Fix handling exception

### PR DESCRIPTION
**Pull request by dblN**
The codes inside `else` are executed if no exception throws in `try`. If I get it right, these lines are expected to catch any exception other than `IOError` and `ValueError`. So, I replace `else` with `except`.

### CODE REVIEW

**Comment by k4nar** [comment]
Indeed, nice catch! However, I think we should have `except Exception as e` and print the exception in the message. Because if we get there, it's because we have some nasty error. I's not because the file is inaccessible or is not a valid JSON file, so it must be more like an alien attack or something :) .

**Comment by dblN** [comment]
@k4nar ok. then, something like this?
```python
...
except Exception as e:
    raise WatsonError(
        "Unexpected error while loading JSON file {}: {}".format(filename, e)
    )
...
```

**Comment by k4nar** [comment]
Yes exactly :) .

**Comment by k4nar** [comment]
Thanks :+1: !

**Pull request merged**
